In [1]:
import pandas as pd

df = pd.read_csv("Banking.csv")

df.head()

,Client ID,Name,Age,Location ID,Joined Bank,Banking Contact,Nationality,Occupation,Fee Structure,Loyalty Classification,...,Bank Deposits,Checking Accounts,Saving Accounts,Foreign Currency Account,Business Lending,Properties Owned,Risk Weighting,BRId,GenderId,IAId
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5

In [2]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(r"[^a-z0-9]+", "_", regex=True)
      .str.strip("_")
)

In [3]:
df

,client_id,name,age,location_id,joined_bank,banking_contact,nationality,occupation,fee_structure,loyalty_classification,...,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,brid,genderid,iaid
0,IND81288,Raymond Mills,24,34324,06-05-2019,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,10-12-2001,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,25-01-2010,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,28-03-2019,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,20-07-2012,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,IND66827,Earl Hall,82,8760,09-10-2014,Joshua Bennett,American,Accounting Assistant III,High,Gold,...,1089957.03,532867.88,657849.62,12947.31,1238859.91,1,3,3,2,4
2996,IND40556,Billy Williamson,44,32837,05-02-2009,Dennis Ruiz,European,Paralegal,Mid,Gold,...,136891.32,56581.74,93195.61,23205.69,277171.07,1,2,3,2,5
2997,IND72414,Victor Black,70,36088,29-12-2009,Joshua Ryan,American,Statistician IV,Low,Jade,...,214860.89,158726.06,35539.15,30291.81,502947.22,2,2,3,2,6
2998,IND46652,Andrew Ford,56,24871,13-02-2006,Nicholas Cunningham,European,Human Resources Assistant III,Mid,Jade,...,742630.22,404638.26,56411.33,6413.14,1538368.60,3,1,3,2,7
2999,IND40216,Amy Nguyen,79,38518,08-12-2005,Joe Hanson,American,Biostatistician III,High,Jade,...,65617.66,77769.08,32371.38,8992.36,329412.55,1,1,3,2,8

In [4]:
df["joined_bank"] = pd.to_datetime(
    df["joined_bank"],
    format="%d-%m-%Y"
)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   client_id                 3000 non-null   str
 1   name                      3000 non-null   str
 2   age                       3000 non-null   int64
 3   location_id               3000 non-null   int64
 4   joined_bank               3000 non-null   datetime64[us]
 5   banking_contact           3000 non-null   str
 6   nationality               3000 non-null   str
 7   occupation                3000 non-null   str
 8   fee_structure             3000 non-null   str
 9   loyalty_classification    3000 non-null   str
 10  estimated_income          3000 non-null   float64
 11  superannuation_savings    3000 non-null   float64
 12  amount_of_credit_cards    3000 non-null   int64
 13  credit_card_balance       3000 non-null   float64
 14  bank_loans                3000 non-null   float64
 15  bank_deposits             3000 non-null   float64
 16  checking_accounts         3000 non-null   float64
 17  saving_accounts           3000 non-null   float64
 18  foreign_currency_account  3000 non-null   float64
 19  business_lending          3000 non-null   float64
 20  properties_owned          3000 non-null   int64
 21  risk_weighting            3000 non-null   int64
 22  brid                      3000 non-null   int64
 23  genderid                  3000 non-null   int64
 24  iaid                      3000 non-null   int64
dtypes: datetime64[us](1), float64(9), int64(8), str(7)
memory usage: 786.0 KB

In [5]:
%pip install sqlalchemy "psycopg[binary]"

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg[binary]
  Downloading psycopg-3.3.4-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.3-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\anuko\anaconda3\envs\data\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: tzdata in c:\Users\anuko\anaconda3\envs\data\Lib\site-packages (from psycopg[binary]) (2026.2)
Collecting psycopg-binary==3.3.4 (from psycopg[binary])
  Downloading psycopg_binary-3.3.4-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Downloading sqlalchemy-2.0.51-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 10.1 MB/s  0:00:00
Downloading psycopg-3.3.4-py3-none-any.whl (213 kB)
Downloading psycopg_binary-3.3.4-cp311-cp311-win_amd64.whl (3.6 MB)
   ---------------------------------------- 0.0/3.6 MB ? eta -:--:--
   ---------------------------------------- 3.6/3.6 MB 35.2 MB/s  0:00:00
Downloading greenlet-3.5.3-cp311-cp311-win_amd64.whl (239 kB)
Installing collected packages: psycopg-binary, psycopg, greenlet, sqlalchemy

   ---------------------------------------- 0/4 [psycopg-binary]
   ---------- ----------------------------- 1/4 [psycopg]
   ---------- ----------------------------- 1/4 [psycopg]
   ---------- ----------------------------- 1/4 [psycopg]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ---------------------------------------- 4/4 [sqlalchemy]

Successfully installed greenlet-3.5.3 psycopg-3.3.4 psycopg-binary-3.3.4 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [6]:
from sqlalchemy import create_engine, URL
from getpass import getpass

password = getpass("Enter PostgreSQL password: ")

url = URL.create(
    drivername="postgresql+psycopg",
    username="postgres",
    password=password,
    host="localhost",
    port=5432,
    database="banking_project"
)

engine = create_engine(url)

In [7]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT current_database();"))
    print(result.fetchone())

('banking_project',)

In [8]:
df.to_sql(
    name="banking_customers",
    con=engine,
    schema="public",
    if_exists="replace",
    index=False,
    chunksize=1000
)

print("Table created and data inserted successfully.")

Table created and data inserted successfully.