<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/2_04_Pandas Pivot Tables.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:134: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

## 🟩 Count Job Postings by Title and Country (2.4.1)

In [2]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [7]:
job_posting = df.pivot_table(values='job_posted_date',index='job_title_short',columns='job_country',aggfunc='count');
job_posting

job_country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,...,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
job_title_short,,,,,,,,,,,,,,,,,,,,,
Business Analyst,4.0,11.0,21.0,1.0,453.0,29.0,928.0,738.0,16.0,5.0,...,984.0,827.0,7382.0,199.0,55.0,2.0,91.0,3.0,30.0,6.0
Cloud Engineer,NaN,1.0,5.0,NaN,322.0,4.0,489.0,266.0,NaN,2.0,...,93.0,193.0,423.0,53.0,3.0,2.0,70.0,NaN,4.0,3.0
Data Analyst,9.0,36.0,22.0,2.0,1273.0,33.0,1658.0,2169.0,21.0,7.0,...,2587.0,10482.0,67816.0,227.0,39.0,16.0,334.0,4.0,40.0,34.0
Data Engineer,NaN,30.0,21.0,3.0,2265.0,45.0,4658.0,2175.0,7.0,14.0,...,1139.0,11807.0,35080.0,248.0,49.0,19.0,768.0,2.0,5.0,11.0
Data Scientist,1.0,12.0,27.0,1.0,1617.0,28.0,1179.0,1709.0,16.0,5.0,...,1360.0,9148.0,58830.0,140.0,50.0,9.0,375.0,NaN,13.0,13.0
Machine Learning Engineer,NaN,4.0,2.0,NaN,287.0,22.0,360.0,305.0,2.0,3.0,...,164.0,317.0,921.0,46.0,22.0,4.0,115.0,NaN,2.0,1.0
Senior Data Analyst,2.0,2.0,NaN,NaN,255.0,22.0,310.0,301.0,2.0,1.0,...,262.0,1356.0,11791.0,50.0,15.0,4.0,71.0,NaN,5.0,1.0
Senior Data Engineer,NaN,6.0,1.0,NaN,647.0,57.0,1482.0,542.0,4.0,12.0,...,227.0,3337.0,9289.0,106.0,54.0,4.0,220.0,NaN,NaN,3.0
Senior Data Scientist,NaN,11.0,NaN,1.0,350.0,16.0,302.0,451.0,1.0,1.0,...,245.0,2367.0,12946.0,54.0,19.0,3.0,91.0,NaN,2.0,1.0
Software Engineer,NaN,6.0,12.0,3.0,1267.0,33.0,1589.0,1054.0,14.0,19.0,...,480.0,541.0,1814.0,263.0,27.0,6.0,279.0,1.0,3.0,8.0

---

## 🟨 Salary Stats by Job Title (2.4.2)

In [8]:
salary_stats = df.groupby('job_title_short')['salary_year_avg'].describe();
display(salary_stats)

,count,mean,std,min,25%,50%,75%,max
job_title_short,,,,,,,,
Business Analyst,610.0,91082.612833,32036.098388,16500.0,70320.0,85000.0,105000.000,387460.0
Cloud Engineer,65.0,111268.453846,50514.351080,42000.0,79200.0,90000.0,136000.000,280000.0
Data Analyst,5451.0,93841.907854,34100.108034,25000.0,70000.0,90000.0,111175.000,650000.0
Data Engineer,4500.0,130125.604250,42525.929674,15000.0,100000.0,125000.0,147500.000,525000.0
Data Scientist,5922.0,135988.837171,52227.832196,27000.0,100000.0,127500.0,158917.875,960000.0
Machine Learning Engineer,576.0,126774.315972,53914.993342,30000.0,80850.0,106415.0,166000.000,325000.0
Senior Data Analyst,1131.0,113911.363665,34060.065096,30000.0,92500.0,111175.0,125000.000,425000.0
Senior Data Engineer,1591.0,145840.611624,37415.120392,35000.0,125000.0,147500.0,167174.000,425000.0
Senior Data Scientist,1690.0,154206.292996,50927.738257,45000.0,125000.0,155500.0,174000.000,890000.0
Software Engineer,467.0,113393.760054,51624.385181,28000.0,79200.0,99150.0,149826.500,375000.0

In [11]:
salary_stat = df.pivot_table(values='salary_year_avg' , index='job_title_short',aggfunc=['min','max','count','median'])
salary_stat

,min,max,count,median
,salary_year_avg,salary_year_avg,salary_year_avg,salary_year_avg
job_title_short,,,,
Business Analyst,16500.0,387460.0,610,85000.0
Cloud Engineer,42000.0,280000.0,65,90000.0
Data Analyst,25000.0,650000.0,5451,90000.0
Data Engineer,15000.0,525000.0,4500,125000.0
Data Scientist,27000.0,960000.0,5922,127500.0
Machine Learning Engineer,30000.0,325000.0,576,106415.0
Senior Data Analyst,30000.0,425000.0,1131,111175.0
Senior Data Engineer,35000.0,425000.0,1591,147500.0
Senior Data Scientist,45000.0,890000.0,1690,155500.0
Software Engineer,28000.0,375000.0,467,99150.0

---

## 🟥 Sum Salary by Title and Country (2.4.3)

In [14]:
sum_salary = df.pivot_table(values='salary_year_avg',index='job_title_short',columns='job_country',aggfunc='sum' , fill_value=0)
sum_salary

job_country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,...,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
job_title_short,,,,,,,,,,,,,,,,,,,,,
Business Analyst,0.0,0.0,0.0,0.0,142200.0,0.0,263000.0,0.0,0.0,0.0,...,0.0,247800.0,4.145162e+07,0.0,0.0,0.0,223200.0,0.0,0.0,0.0
Cloud Engineer,0.0,0.0,0.0,0.0,197500.0,0.0,110000.0,0.0,0.0,0.0,...,0.0,0.0,2.401818e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Data Analyst,0.0,99900.0,44100.0,0.0,341745.5,201000.0,411500.0,378496.0,0.0,0.0,...,459375.0,6437586.0,4.113097e+08,100500.0,0.0,0.0,999267.0,0.0,0.0,63000.0
Data Engineer,0.0,0.0,45000.0,0.0,1225599.0,97500.0,3374399.5,405000.0,0.0,1755244.0,...,752992.5,6937332.0,3.912708e+08,0.0,0.0,0.0,1576131.0,0.0,0.0,0.0
Data Scientist,0.0,139962.5,0.0,0.0,597221.5,0.0,978291.0,142499.5,0.0,0.0,...,166419.5,8268820.0,6.371774e+08,0.0,30750.0,0.0,534400.0,0.0,90670.0,138170.0
Machine Learning Engineer,0.0,0.0,0.0,0.0,393029.0,174042.0,856129.0,178200.0,0.0,457500.0,...,125700.0,976951.0,1.974277e+07,50000.0,0.0,0.0,571050.0,0.0,0.0,0.0
Senior Data Analyst,0.0,0.0,0.0,0.0,0.0,0.0,101280.0,178200.0,0.0,0.0,...,421350.0,858515.0,1.056607e+08,0.0,0.0,0.0,402050.0,0.0,0.0,0.0
Senior Data Engineer,0.0,0.0,0.0,0.0,295000.0,0.0,1079046.0,531600.0,0.0,1287500.0,...,0.0,3301200.5,1.602320e+08,0.0,0.0,0.0,508500.0,0.0,0.0,0.0
Senior Data Scientist,0.0,157500.0,0.0,0.0,0.0,0.0,787500.0,80850.0,0.0,0.0,...,216000.0,4011376.0,1.977291e+08,57500.0,0.0,0.0,79200.0,0.0,0.0,0.0
Software Engineer,0.0,0.0,0.0,0.0,174500.0,0.0,843935.0,0.0,72000.0,731500.0,...,79200.0,516400.0,2.166049e+07,0.0,0.0,0.0,107200.0,0.0,0.0,0.0

---